### ISSUE TITLE
这个消息组件没有简单的说明文档吗？

### ISSUE THREAD

**Issue by loveyeguo** [NewLifeX/NewLife.RocketMQ#11]
示例中：NameServerAddress = "10.9.20.106:9876",  在我自己机器应该怎么部署这个服务

**Comment by nnhy** [comment]
需要自己去安装 RocketMQ 服务端，这里的newlife.rocketmq只是客户端

**Comment by nnhy** [comment]
消息队列NewLife.RocketMQ · 语雀
https://www.yuque.com/smartstone/nx/rocketmq
