### ISSUE TITLE
怎么停止已启动的consumer

### ISSUE THREAD

**Issue by wingqing1314** [NewLifeX/NewLife.RocketMQ#15]
如题，调用consumer.start()后一段时间后，尝试调用consumer.dispose()，仍然不能停止消费

**Comment by nnhy** [comment]
按照设计，dispose时会停止线程和定时器，应该会停止小飞

**Comment by xyyipiantian** [comment]
同样 问题 RocketMQ 管理网页 还是可以看到 消费者存在，线程没有取消一样
