### ISSUE TITLE
这个是TCP连接吗？

### ISSUE THREAD

**Issue by JHeLiu** [NewLifeX/NewLife.RocketMQ#17]
这个是TCP连接吗？

**Comment by nnhy** [comment]
对，直接tcp连接

**Comment by JHeLiu** [comment]
@nnhy  这个库不依赖 ONSClient4CPP.dll 我好奇是不是迁移了 C++的？

**Comment by nnhy** [comment]
RocketMQ原来只有唯一一个.net客户端，就是阿里云公开的那个，嵌入C++的DLL。
那个组件有个稳定性问题，跑久了可能进程退出。

然后我们从零开始设计了 NewLife.RocketMQ，从阅读RocketMQ报文协议开始，但是进度太慢了，于是了解到打包结构以后，直接抓包逆向，最终实现了三五个指令，足够生产消费与再平衡。
最后多花了一倍的时间，主要在于阿里云RocketMQ的验证算法上，比较复杂一些。

**Comment by JHeLiu** [comment]
哎，阿里云那个SDK 真的没法看， 用微软云的SDK C# JAVA的 SDK都提供而且几乎都写的非常好，  阿里云的貌似就JAVA，连C++的都不上心。  

我很奇怪的是 不想写SDK ，为什么不能像 微信公众号那样，直接给文档，让开发者自己去写

**Comment by nnhy** [comment]
有文档的，但是太长了，大量指令是服务端使用的，用于维护集群。
客户端只需要几个指令足够了，所以可以做得非常轻量级。
