### ISSUE TITLE
MsgId的值指的是RocketMq控制台的MessageId吗

### ISSUE THREAD

**Issue by christan-duplicate** [NewLifeX/NewLife.RocketMQ#23]
请问为什么我获取到的msgid和RocketMq控制台的MessageId不一样呢，如果我想获取MessageId应该用哪个属性？

**Comment by nnhy** [comment]
按照RocketMQ协议，MsgId就是消息编号，它是一个二进制数据，我们把它做了HEX编码处理，控制台有可能使用长整型

**Comment by christan-duplicate** [comment]
比如，MsgId获到的是：7516B6D0000009DA000000000D06B6F3
而RocketMq控制台显示的是：AC110001000141CF53F959FF73AE001C
请问有什么方法转成RocketMq控制台的格式吗？

**Comment by nnhy** [comment]
那就尴尬了。。。两个Id还是一样长度，应该不是我说的问题，可能真的就是两个不同的数字

AC110001 =>  172.17.0.1
可能是这个，比较熟悉

**Comment by christan-duplicate** [comment]
是啊，我就发现应该都是hex，但是值又不一样，所以我这边无法用msgid查到对应的消息。。。

**Comment by nnhy** [comment]
这个问题，后来有进展吗？

**Comment by christan-duplicate** [comment]
> 这个问题，后来有进展吗？

没有好的方法，后来用其他字段代理了

**Comment by nnhy** [comment]
经过确认，发布消息后得到的MsgId，能够在rocketmq控制台查到消息

**Comment by christan-duplicate** [comment]
> 经过确认，发布消息后得到的MsgId，能够在rocketmq控制台查到消息

感谢，真的可以，不知道之前为什么查不到！！！
