### ISSUE TITLE
调用阿里云(tcp) Producer和 Consumer 都报topic route info in name server for the topic: guanzhu

### ISSUE THREAD

**Issue by liuhang798** [NewLifeX/NewLife.RocketMQ#24]
14:39:23.710  1 N - [Name]集群地址：Http://****aliyuncs.com:80
14:39:23.720  1 N - [Name]正在连接[Http://****aliyuncs.com:80]
14:39:23.733  1 N - Tcp.Open Tcp://0.0.0.0:51925=>118.190.213.147:80
14:39:23.954  1 N - NewLife.Core v8.10.2021.0101 Build 2021-01-01 19:31:46 .NET Framework 4.6
14:39:23.955  1 N - X组件核心库 ?2002-2020 NewLife
14:39:23.956  1 N - MqProducer v1.0.0.0 Build 2000-01-01 .NET Framework 4.7.2
14:39:23.957  1 N - MqProducer Copyright ?  2021
14:39:23.983  1 N - NewLife.RocketMQ.Protocol.ResponseException: 17: **### No topic route info in name server for the topic: guanzhu**
See http://rocketmq.apache.org/docs/faq/ for further details.
   在 NewLife.RocketMQ.ClusterClient.Invoke(RequestCode request, Object body, Object extFields, Boolean ignoreError) 位 置 D:\X\NewLife.RocketMQ\NewLife.RocketMQ\ClusterClient.cs:行号 216
   在 NewLife.RocketMQ.NameClient.GetRouteInfo(String topic) 位置 D:\X\NewLife.RocketMQ\NewLife.RocketMQ\NameClient.cs: 行号 66
   在 NewLife.RocketMQ.Client.MqBase.Start() 位置 D:\X\NewLife.RocketMQ\NewLife.RocketMQ\MqBase.cs:行号 154
   在 NewLife.RocketMQ.Producer.Start() 位置 D:\X\NewLife.RocketMQ\NewLife.RocketMQ\Producer.cs:行号 36
   在 MqProducer.Program.Main(String[] args) 位置 D:\工作\MQ\Demo\rocketMQ\rocketMQDemo\MqProducer\Program.cs:行号 34
14:39:23.984  1 N - 异常退出！

**Comment by liuhang798** [comment]
实际上我是有这个topic，不知道问题出在了那里

**Comment by Guma-Ark** [comment]
调用阿里云RocketMQ时NewLife的设置如下

**Comment by Guma-Ark** [comment]
调用阿里云RocketMQ时NewLife的设置如下
 var mq = new Producer
 {
    //这里不能只设置阿里云控制台看到的Topic，需要加上实例ID，百分号隔开
    Topic = $"{实例ID}%{Topic}",
	NameServerAddress ="Tcp接入点（公网）"
 };
