### ISSUE TITLE
This RocketMQ client support Sendwait?

### ISSUE THREAD

**Issue by tobepeople** [NewLifeX/NewLife.RocketMQ#25]
I am trying to develop c# client using NewLife.RocketMQ and it should implement send/wait scenario. Dose it support?

**Comment by nnhy** [comment]
It do'nt support wait。By the way，you can publish message before subcribe another topic.

**Comment by nnhy** [comment]
增加异步消费以及事件修复 fix: 44 · NewLifeX/NewLife.RocketMQ@564ae4f
https://github.com/NewLifeX/NewLife.RocketMQ/commit/564ae4f60e6e86809bf8a4fa13ea886ebbafa031
