### ISSUE TITLE
可以关闭vip通道吗

### ISSUE THREAD

**Issue by spacestime** [NewLifeX/NewLife.RocketMQ#26]
可以关闭vip通道吗

**Comment by spacestime** [comment]
![image](https://user-images.githubusercontent.com/17666651/112504686-fb0e6e00-8dc6-11eb-9ac5-187586f3e278.png)
看代码好像注销了

**Comment by nnhy** [comment]
并没有使用Vip通道，我们认为内网通信足够稳定可靠，一般情况下用不到Vip通道
