### ISSUE TITLE
阿里云rocketmq如何配置

### ISSUE THREAD

**Issue by jovi-Li** [NewLifeX/NewLife.RocketMQ#29]
阿里云如何配置，获取不到nameserver

**Comment by jovi-Li** [comment]
原来是tcp协议的； 
配置了 
Topic = "*",
  Group = "*",
  NameServer = "*:80",
  AccessKey = "*",
  SecretKey = "*",
报错:
17: No topic route info in name server for the topic:

**Comment by nnhy** [comment]
配置文件 config/RocketMQ.config，里面有个Server，设置为阿里云地址，例如 http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
