### ISSUE TITLE
消费者不消费

### ISSUE THREAD

**Issue by nodyang** [NewLifeX/NewLife.RocketMQ#3]
14:06:12.276 49 Y - Tcp.OnReceiveError Tcp://0.0.0.0:54104=>ip:10911 未将对象引用设置到对象的实例。  http://git.newlifex.com/NewLife/NewLife.RocketMQ  最新版本然后消费者就不消费了。nuget 版本正常。

**Comment by nodyang** [comment]
#Software: Test
#ProcessID: 1316 x64
#AppDomain: Test.exe
#BaseDirectory: D:\software\git\net\NewLife.RocketMQ\BinTest\
#CommandLine: "D:\software\git\net\NewLife.RocketMQ\BinTest\Test.exe" 
#ApplicationType: Console
#CLR: 4.0.30319.42000, .NET Framework 4.6.1
#OS: Microsoft Windows NT 6.2.9200.0, PC201902190935Q/Administrator
#CPU: 4
#GC: IsServerGC=False, LatencyMode=Interactive
#Date: 2019-03-07
#字段: 时间 线程ID 线程池Y网页W普通N 线程名 消息内容
#Fields: Time ThreadID IsPoolThread ThreadName Message
14:32:42.567  1 N - NewLife.Core v8.0.2019.0101 Build 2019-01-26 23:22:28 .NET Framework 4.5
14:32:42.573  1 N - 组件核心库 版权所有(C) 2002-2019 新生命开发团队 https://github.com/NewLifeX/X
14:32:42.578  1 N - Test v1.0.0.0 Build 2000-01-01 .NET Framework 4.6.1
14:32:42.578  1 N - Test Copyright ©  2018
14:32:42.966  6 Y 1 发现Broker[linuxserver]: 120.221.85.185:10911
14:32:42.967  1 N - 发现Broker[linuxserver]: 120.221.85.185:10911
14:32:43.086 14 Y T [linuxserver]集群地址：120.221.85.185:10911
14:32:43.088 14 Y T [linuxserver]正在连接[://120.221.85.185:10911]
14:32:43.091 14 Y T Tcp.Open Tcp://0.0.0.0:55019=>120.221.85.185:10911
14:32:43.129 14 Y T [linuxserver]=> GET_CONSUMER_LIST_BY_GROUP(1)[0]
14:32:43.144 13 Y - [linuxserver]<= #SYSTEM_ERROR(1)[0]
14:32:43.214 14 Y T [yangGropu]1: no consumer for this group
14:32:43.233  3 N T [linuxserver]=> HEART_BEAT(2)[400]
14:32:43.243 11 Y - [linuxserver]收到：Code=NOTIFY_CONSUMER_IDS_CHANGED {"code":40,"extFields":{"consumerGroup":"yangGropu"},"flag":2,"language":"JAVA","opaque":347190,"serializeTypeCurrentRPC":"JSON","version":293,"remark":null}
14:32:43.249 14 Y - [linuxserver]<= #SUCCESS(2)[0]
14:32:43.250 16 Y - [linuxserver]=> GET_CONSUMER_LIST_BY_GROUP(3)[0]
14:32:43.279  7 Y - [linuxserver]<= #SUCCESS(3)[39]
14:32:43.288 16 Y - [yangGropu]消费重新平衡：linuxserver[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
14:32:43.394 19 N CT0 [linuxserver]=> QUERY_CONSUMER_OFFSET(4)[0]
14:32:43.395 21 N CT2 [linuxserver]=> QUERY_CONSUMER_OFFSET(5)[0]
14:32:43.395 20 N CT1 [linuxserver]=> QUERY_CONSUMER_OFFSET(6)[0]
14:32:43.428 15 Y - [linuxserver]<= #SUCCESS(4)[0]
14:32:43.428 14 Y - [linuxserver]<= #SUCCESS(5)[0]
14:32:43.429 19 N CT0 [yangGropu]开始消费[linuxserver@0] Offset=8,676
14:32:43.432 21 N CT2 [yangGropu]开始消费[linuxserver@2] Offset=8,670
14:32:43.452 18 Y - [linuxserver]<= #SUCCESS(6)[0]
14:32:43.454 20 N CT1 [yangGropu]开始消费[linuxserver@1] Offset=8,671
14:32:43.465 22 N CT3 [linuxserver]=> QUERY_CONSUMER_OFFSET(7)[0]
14:32:43.518 23 N CT4 [linuxserver]=> QUERY_CONSUMER_OFFSET(8)[0]
14:32:43.519 15 Y - [linuxserver]<= #SUCCESS(7)[0]
14:32:43.540 22 N CT3 [yangGropu]开始消费[linuxserver@3] Offset=8,670
14:32:43.595 25 N CT5 [linuxserver]=> QUERY_CONSUMER_OFFSET(9)[0]
14:32:43.664 15 Y - [linuxserver]<= #SUCCESS(8)[0]
14:32:43.772 22 N CT3 [linuxserver]=> PULL_MESSAGE(10)[0]
14:32:43.775 20 N CT1 [linuxserver]=> PULL_MESSAGE(12)[0]
14:32:43.776 19 N CT0 [linuxserver]=> PULL_MESSAGE(13)[0]
14:32:43.779 21 N CT2 [linuxserver]=> PULL_MESSAGE(11)[0]
14:32:43.880 26 Y - [linuxserver]<= #SUCCESS(9)[0]
14:32:43.887 23 N CT4 [yangGropu]开始消费[linuxserver@4] Offset=8,670
14:32:43.890 23 N CT4 [linuxserver]=> PULL_MESSAGE(15)[0]
14:32:43.895 25 N CT5 [yangGropu]开始消费[linuxserver@5] Offset=8,666
14:32:43.899 25 N CT5 [linuxserver]=> PULL_MESSAGE(16)[0]
14:32:43.903 28 N CT6 [linuxserver]=> QUERY_CONSUMER_OFFSET(14)[0]
14:32:44.001 29 N CT7 [linuxserver]=> QUERY_CONSUMER_OFFSET(17)[0]
14:32:44.053 30 N CT8 [linuxserver]=> QUERY_CONSUMER_OFFSET(18)[0]
14:32:44.272 33 N CT11 [linuxserver]=> QUERY_CONSUMER_OFFSET(21)[0]
14:32:44.274 35 N CT13 [linuxserver]=> QUERY_CONSUMER_OFFSET(20)[0]
14:32:44.277 31 N CT9 [linuxserver]=> QUERY_CONSUMER_OFFSET(23)[0]
14:32:44.286 32 N CT10 [linuxserver]=> QUERY_CONSUMER_OFFSET(22)[0]
14:32:44.290 34 N CT12 [linuxserver]=> QUERY_CONSUMER_OFFSET(19)[0]
14:32:44.324 36 N CT14 [linuxserver]=> QUERY_CONSUMER_OFFSET(24)[0]
14:32:44.331 37 N CT15 [linuxserver]=> QUERY_CONSUMER_OFFSET(25)[0]
14:33:13.251  3 N T [linuxserver]=> HEART_BEAT(26)[400]
14:33:13.258  6 Y - [linuxserver]<= #SUCCESS(26)[0]
14:33:15.264 17 Y T [linuxserver]=> GET_CONSUMER_LIST_BY_GROUP(27)[0]
14:33:15.269  6 Y - [linuxserver]<= #SUCCESS(27)[39]
14:33:43.474 43 Y - Tcp.Close TcpSessionDispose Tcp://0.0.0.0:55019=>120.221.85.185:10911
14:33:43.725  3 N T [linuxserver]=> HEART_BEAT(28)[400]
14:33:44.097  3 N T [linuxserver]正在连接[Tcp://120.221.85.185:10911]
14:33:44.097 22 N CT3 [linuxserver]=> PULL_MESSAGE(29)[0]
14:33:44.101 29 N CT7 [linuxserver]=> QUERY_CONSUMER_OFFSET(30)[0]
14:33:44.102 23 N CT4 [linuxserver]=> PULL_MESSAGE(32)[0]
14:33:44.112 28 N CT6 [linuxserver]=> QUERY_CONSUMER_OFFSET(31)[0]
14:33:44.114 25 N CT5 [linuxserver]=> PULL_MESSAGE(33)[0]
14:33:44.155 19 N CT0 [linuxserver]=> PULL_MESSAGE(35)[0]
14:33:44.297 20 N CT1 [linuxserver]=> PULL_MESSAGE(34)[0]
14:33:44.305 30 N CT8 [linuxserver]=> QUERY_CONSUMER_OFFSET(36)[0]
14:33:44.311 21 N CT2 [linuxserver]=> PULL_MESSAGE(37)[0]
14:33:44.296  3 N T Tcp.Open Tcp://0.0.0.0:55048=>120.221.85.185:10911
14:33:44.403 40 Y - [linuxserver]收到：Code=NOTIFY_CONSUMER_IDS_CHANGED {"code":40,"extFields":{"consumerGroup":"yangGropu"},"flag":2,"language":"JAVA","opaque":348037,"serializeTypeCurrentRPC":"JSON","version":293,"remark":null}
14:33:44.515 45 Y - [linuxserver]=> GET_CONSUMER_LIST_BY_GROUP(38)[0]
14:33:44.899 14 Y - [linuxserver]<= #SUCCESS(28)[0]
14:33:44.972 32 N CT10 [linuxserver]=> QUERY_CONSUMER_OFFSET(39)[0]
14:33:45.015 36 N CT14 [linuxserver]=> QUERY_CONSUMER_OFFSET(40)[0]
14:33:45.047 34 N CT12 [linuxserver]=> QUERY_CONSUMER_OFFSET(41)[0]
14:33:45.168 33 N CT11 [linuxserver]=> QUERY_CONSUMER_OFFSET(42)[0]
14:33:45.171 31 N CT9 [linuxserver]=> QUERY_CONSUMER_OFFSET(43)[0]
14:33:45.173 35 N CT13 [linuxserver]=> QUERY_CONSUMER_OFFSET(45)[0]
14:33:45.181 37 N CT15 [linuxserver]=> QUERY_CONSUMER_OFFSET(44)[0]
14:33:45.195  3 N T 任务 BrokerClient.OnPing 耗时过长 1,540ms，建议使用异步任务Async=true
14:33:45.221 48 Y - Tcp.OnReceiveError Tcp://0.0.0.0:55048=>120.221.85.185:10911 未将对象引用设置到对象的实例。

**Comment by nnhy** [comment]
源码最新版可能还有bug，编码器兼容问题

**Comment by nnhy** [comment]
编码器兼容BUG已修正，已发布nuget
