### ISSUE TITLE
Consumer的FromLastOffset问题

### ISSUE THREAD

**Issue by inversionhourglass** [NewLifeX/NewLife.RocketMQ#33]
请问`Consumer.FromLastOffset`的设定是不是对应java原版里的`ConsumeFromWhere`，看名字应该是这个意思，但是看源码实现没有达到这个效果，并且没有`ConsumeFromWhere`的相关实现。
https://github.com/NewLifeX/NewLife.RocketMQ/blob/aa267cd8df8cdb2e8aa07dac0b8df7e0a0b62ec7/NewLife.RocketMQ/Consumer.cs#L385-L406
上面这段代码截取自`DoPull`方法，首先明确一点，在`DoPull`首次被调用时`QueueStore.Offset`取到的值必定是-1。然后根据上面这部分代码：
`FromLastOffset=false`：
> 首次运行`offset`取值必定为0。这样应用每次重启就必须重新消费，但ConsumeFromWhere是针对首次消费的配置，也就是group创建后的首次消费，重启应用后不再判断该配置，应该在之前的offset继续消费

 `FromLastOffset=true & SkipOverStoredMsgCount<=0`：
> 首次运行时`offset`从broker取当前消费offset。这个对之前有过消费记录的没有问题，但对首次消费来说`QueryOffset`查询到的一定是0，这样也就需要重头开始消费，这和`FromLastOffset=true`不符，理论应该`FromLastOffset=true`时首次消费从最大偏移量开始消费，反之从0开始

 `FromLastOffset=true & SkipOverStoredMsgCount>0`：
> 首次运行时将`offset + SkipOverStoredMsgCount`与`maxOffset`进行对比，这样存在两种情况
> 1.首次消费，如果最大偏移量大于最大积压数量，那么就从最大偏移量开始消费，反之从0开始消费
> 2.非首次消费，如果最大偏移量大于当前偏移量+最大积压数量，那么就从最大偏移量开始消费，反之从当前偏移量开始消费
> 第一种情况有可能从0开始消费，与`FromLastOffset=true`定义不符，第二种情况按照你`SkipOverStoredMsgCount`的设定是没问题的

按照“`FromLastOffset=true`时首次消费从最大偏移量开始消费，反之从0开始消费，非首次消费从上一次消费的偏移量继续消费”的逻辑，我自己重新改了一下代码，完成后准备提交一个pullrequest，现在有一个问题需要跟作者讨论一下，`SkipOverStoredMsgCount`这个配置应该是你自己定义的吧，官方应该没有这个配置，我认为在已经消费过的情况下，即使有积压也不应该通过一个配置进行自动跳过，应该由人工判断后手动跳过，自动的风险太大，所以我更改后的逻辑是只在首次消费且`FromLastOffset=false`时才判断积压情况，这样就是在首次消费时，如果期望从头开始收，但发现从头开始数据量过大，那么就从尾开始收，同时因为这个配置是自定义的，我认为默认应该保持与官方一致，避免使用的人在不知情的情况下做出了与官方不一样的操作，所以我认为将`SkipOverStoredMsgCount`的默认值设置为0更合适。作者你看看`SkipOverStoredMsgCount`按我上面说的这个逻辑改是否可行，如果可行我就准备提交pullrequest了，如果有不妥的地方你说说你的想法，确定后我再提交pullrequest

**Comment by nnhy** [comment]
默认 FromLastOffset 等同于 ConsumeFromWhere 的 CONSUME_FROM_LAST_OFFSET，表示从上一次最后消费处继续开始消费。

**Comment by nnhy** [comment]
SkipOverStoredMsgCount 由社区同学提交合并进去，最近默认值修改为0

**Comment by nnhy** [comment]
ConsumeFromWhere 官方用法的确非常麻烦，如果完全准确，可能会让很多rocketmq初学者觉得难以适从。
从实际经验来看，最近几年使用 newlife.rocketmq 的用户，有90%以上根本就不会 rocketmq，也没有去看过相关文档，只需要代码能跑起来即可。

**Comment by inversionhourglass** [comment]
`FromLastOffset`默认为`true`在首次消费时即使队列里已有消息，依旧会从0开始消费，非首次消费的情况下能够正常运行。我更改后的代码默认也是`CONSUME_FROM_LAST_OFFSET`，现在代码在另一个电脑上，我明天提交一个pullrequest，你先看一下。我们公司现在要改用rocketmq，.NET端的SDK看了下只有你们newlife是持续更新的

**Comment by inversionhourglass** [comment]
pullrequest已经提交了，我又想了一下，还是保留了SkipOverStoredMsgCount的原始逻辑，有这样的逻辑可能是有这样的场景需要，但是由于这个会破坏FromLastOffset的原始意图，所以我把它标记为Obsolete用于提醒，避免误使用

**Comment by inversionhourglass** [comment]
#34

**Comment by inversionhourglass** [comment]
现在提交的代码还有个问题，在CONSUME_FROM_FIRST_OFFSET的时候不应该直接从0开始，因为可能最开始的消息已经过期，我正在想办法测试和查询可用的最小offset
https://github.com/inversionhourglass/NewLife.RocketMQ/blob/9be25bf374e41834ab1c0122565990513e97191d/NewLife.RocketMQ/Consumer.cs#L663

**Comment by nnhy** [comment]
> `FromLastOffset`默认为`true`在首次消费时即使队列里已有消息，依旧会从0开始消费，非首次消费的情况下能够正常运行。我更改后的代码默认也是`CONSUME_FROM_LAST_OFFSET`，现在代码在另一个电脑上，我明天提交一个pullrequest，你先看一下。我们公司现在要改用rocketmq，.NET端的SDK看了下只有你们newlife是持续更新的

这里可能理解有误！
FromLastOffset=true 意思是从最后一次消费位置继续消费。
如果是队列首次消费，不管队列已有多少消息，都是从最小偏移量开始（不一定是0）；
如果不是首次消费，那么会从上一次消费的最后位置开始；
这个特性，完全满足我们日常使用啊！

**Comment by nnhy** [comment]
FromLastOffset=true 意思是从最后一次消费位置继续消费，而不是从最大偏移量开始消费。
众多消息队列里面，唯有MQTT有需要从最大偏移量开始消费的需求场景，其它队列都是从上一次消费的地方，继续消费。

**Comment by inversionhourglass** [comment]
如果你FromLastOffset对应的是原版里ConsumeFromWhere的话，并且我理解没错的话，rocketmq中ConsumeFromWhere对应kafka里的auto.offset.reset，这个配置只有在一个新建一个group第一次进行消费的时候才有效（也就是我所说的首次消费），在首次消费的时候通过这个配置来确定是从头开始消费还是从尾开始消费，如果不是首次消费，那么这个配置是无效的，都会从上一次消费的offset继续消费

**Comment by nnhy** [comment]
嗯，那就可能是我理解错了。
其实我们大多数时候，只需要从上一次消费的offset继续消费。首次消费就从最小偏移量开始

**Comment by inversionhourglass** [comment]
如果是这样，可以在我代码的基础上可以将FromLastOffset的默认值设置为false，这样默认行为就和你们现在的保持一致，代码我建议还是采用我提交的这个代码，不然有些功能就无法实现了。
然后我前面提到的一个问题，消息会过期，这样最小offset就不是0的问题我还在尝试，这个pullrequest你等我这个问题解决后在处理吧

**Comment by nnhy** [comment]
好，你处理好后，重新提交一次PR

**Comment by inversionhourglass** [comment]
我试过了，通过`GET_MIN_OFFSET`可以查询到可用的最小offset，不过我试过之后发现不用特意去再查询一次，你现在的代码已经能处理这个问题了，在使用指定offset拉取不到数据时会返回`OffsetIllegal`，同时会给出下一条消息的offset。之前的pullrequest我又增加了一个commit，就把FromLastOffset的默认值改成了false，另外加了一点日志
