### ISSUE TITLE
Producer和consumer如何使用阿里云rocketMQ

### ISSUE THREAD

**Issue by liangxiao1714** [NewLifeX/NewLife.RocketMQ#35]
刚接触rocketMQ不太懂这个配置，看到这个类库，但是没有使用方面的文档说明

- 不明白NameServer和Server配置，是否二选一
- Server这里对应阿里云rocketMQ的什么地方，是EndPoint还是固定http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
- 这个类库使用TCP还是HTTP方式

```
            NewLife.RocketMQ.Producer producer = new NewLife.RocketMQ.Producer
            {
                AccessKey = AccessKeyId,
                SecretKey = AccessKeySecret,
                Server = EndPoint,
                //此处为阿里云控制台rocketMQ实例下的接入点，分为TCP（只有内网Endpoint）,HTTP（公网和内网为不同Endpoint）
                //是否需要NameServerAddress配置
                Topic = Topic
            };
            producer.Start();
            producer.Publish(new Message
            {
                Keys = "TheKey",
                BodyString = "TheMessage." + DateTime.Now,
                Tags = "TestTag"
            });
            producer.Stop();
```

```
NewLife.RocketMQ.Consumer consumer = new NewLife.RocketMQ.Consumer();
            consumer.Configure(new NewLife.RocketMQ.MqSetting()
            {
                AccessKey = AccessKeyId,
                SecretKey = AccessKeySecret,
                Group = Group,
                Server = EndPoint,
                Topic = Topic
            });
            consumer.OnConsume = (mq, ext) =>
            {
                Console.WriteLine(mq.BrokerName);
                return true;
            };
            consumer.Start();
            Task.Delay(TimeSpan.FromMinutes(10));
            consumer.Stop();
```

**Comment by nnhy** [comment]
RocketMQ本身只需要NameServer即可，但是阿里云多了个Server，是一个http地址，通过这个地址结合appid，可以获得nameserver

**Comment by nnhy** [comment]
阿里云Server是http地址，通过http获得NameServer后，走RocketMQ的tcp链路，做topic查找等操作

消息队列NewLife.RocketMQ · 语雀
https://www.yuque.com/smartstone/nx/rocketmq

**Comment by liangxiao1714** [comment]
> RocketMQ本身只需要NameServer即可，但是阿里云多了个Server，是一个http地址，通过这个地址结合appid，可以获得nameserver

* 使用Server也无法正常使用Exception:No :No topic route info in name server for the topic
* 我确认过topic和appkey,appsecret都没问题，测试手动访问http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet 正常，感觉这个Server应该跟我本身的rocketMQ实例可能不属于同一个nameserver
* 然后使用官方SDK倒是可以正常收发消息，只是觉得官方SDK比较重，使用起来也不够简洁

另外当Server换成官方控制台http接入点时，Exception: One or more errors occurred. (400 Bad Request),暂时看起来官方这个endpoint应该只是用来调用官方SDK时使用
```
var producer = new Producer
            {
                Topic = Topic,
                Server = "http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet",
                AccessKey = AccessKeyId,
                SecretKey = AccessKeySecret
            };
            producer.Log = XTrace.Log;
            try
            {
                producer.Start();

                producer.Publish("message", "tag", "key");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            finally
            {
                producer.Stop();
            }
```

**Comment by nnhy** [comment]
http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet

这个地址返回的就是NameServer地址

**Comment by Guma-Ark** [comment]
调用阿里云RocketMQ时NewLife的设置如下
 var mq = new Producer
 {
    //这里不能只设置阿里云控制台看到的Topic，需要加上实例ID，百分号隔开
    Topic = $"{实例ID}%{Topic}",
	NameServerAddress ="Tcp接入点（公网）"
 };

**Comment by nnhy** [comment]
阿里云目前需要在Topic前面带上实例ID并用【%】连接,组成路由Topic[用来路由到实例Topic]。 fix #24 fix#35 … · NewLifeX/NewLife.RocketMQ@33e58a6
https://github.com/NewLifeX/NewLife.RocketMQ/commit/33e58a6b727f88482b159f5e532864a6591b2a5e
