### ISSUE TITLE
System.ArgumentNullException:“Value cannot be null. ”

### ISSUE THREAD

**Issue by ak476565** [NewLifeX/NewLife.RocketMQ#37]
![微信截图_20210926112206](https://user-images.githubusercontent.com/3871722/134792321-070a84d1-3b64-43f7-8079-94a1ebd5c50c.png)

![微信截图_20210926112341](https://user-images.githubusercontent.com/3871722/134792327-2d57d057-531a-45c9-87a6-0dad87e9e1a5.png)

**Comment by nnhy** [comment]
准备个测试环境，晚上18点左右我调试好一下

**Comment by nnhy** [comment]
你这个错误，可以把日志贴出来

**Comment by nnhy** [comment]
阿里云目前需要在Topic前面带上实例ID并用【%】连接,组成路由Topic[用来路由到实例Topic]。 fix #24 fix#35 … · NewLifeX/NewLife.RocketMQ@33e58a6
https://github.com/NewLifeX/NewLife.RocketMQ/commit/33e58a6b727f88482b159f5e532864a6591b2a5e
