### ISSUE TITLE
请问有实现 OneWay 发送的计划吗？

### ISSUE THREAD

**Issue by shiayoung** [NewLifeX/NewLife.RocketMQ#39]
目前发送方确实不关心消息是否在 Broker 落地，测试发现没有 OneWay 的情况下每次 publish 需要花费 30ms 以上，很多情况下需要 200ms 才能收到 ACK，导致发送方消息堆积。这边没法改变 broker，希望能有 OneWay 或其它曲线救国的实现方式减少请求的耗时。感谢！

**Comment by nnhy** [comment]
这个需求可以理解，你能否找到相关资料？然后晚上我们把功能加进去

**Comment by shiayoung** [comment]
> 这个需求可以理解，你能否找到相关资料？然后晚上我们把功能加进去

有时候需要定时推送，如果用户设定的定时时间比较集中，如果还需要 ACK 的时候，在同一连接上，会出现堵塞的情况。

**Comment by nnhy** [comment]
准备一个rocketmq最新版客户端java源码给我。
过几天发布12月正式版newlife.rocketmq，希望能够赶得上！

**Comment by shiayoung** [comment]
https://github.com/apache/rocketmq/tree/master/client/src/main/java/org/apache/rocketmq/client   麻烦看下这个，谢谢

**Comment by nnhy** [comment]
发布者支持PublishOneway。https://github.com/NewLifeX/NewLife.RocketMQ/issue… · NewLifeX/NewLife.RocketMQ@fb48acb
https://github.com/NewLifeX/NewLife.RocketMQ/commit/fb48acba3f3d3d0ca8a7bbfe6b3605173a1ec6c9
