### ISSUE TITLE
不支持阿里云rocketmq

### ISSUE THREAD

**Issue by pengzai123** [NewLifeX/NewLife.RocketMQ#4]
阿里云rocketmq更新了
目前提示

11

**Comment by pengzai123** [comment]
![image](https://user-images.githubusercontent.com/18717303/54685811-b35b0900-4b52-11e9-814c-e132e3b95e2d.png)

**Comment by pengzai123** [comment]
![image](https://user-images.githubusercontent.com/18717303/54685859-cec61400-4b52-11e9-9daf-506ec655a81e.png)

**Comment by nnhy** [comment]
当前版本代码引用的NewLife.Core有bug，影响了RocketMQ，可下载最新代码编译加入引用。

https://github.com/NewLifeX/X
