### ISSUE TITLE
.NET5 Could not load file or assembly 'NewLife.Core, Version=9.0.8098.19786

### ISSUE THREAD

**Issue by gywei** [NewLifeX/NewLife.RocketMQ#43]
.NET5 环境，已引用
NewLife.Core  9.0.2022.304
NewLife.RocketMQ 2.0.2022.304

启动包找不到引用
System.IO.FileLoadException:“Could not load file or assembly 'NewLife.Core, Version=9.0.8098.19786, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)”

**Comment by nnhy** [comment]
发版时有误，已修改为自动发布，并于今天发布了beta版
