### ISSUE TITLE
支持指定消费模式吗？ 就是指定集群还是广播模式

### ISSUE THREAD

**Issue by voisen** [NewLifeX/NewLife.RocketMQ#46]
支持修改消费模式吗
 1、集群模式（负载均衡模式）
 2、广播模式

**Comment by nnhy** [comment]
这个消费模式，只是一个概念问题。
实际上取决于消费组。
如果你的应用部署多份，每一份都使用相同消费组名称，这个时候就是大家一起分享，集群模式。
如果多个应用，各自的消费组名称不同，每个消费组都将会得到所有消息，也就是一条消息会向每个消费组都投递一次，广播模式。

**Comment by anzhonghui** [comment]
请问一下，为什么两个消费者同一个group会消费重复，如何解决？谢谢

**Comment by nnhy** [comment]
确保是同一个集群同一个topic，拉取到相同broker信息。

**Comment by anzhonghui** [comment]
已解决，谢谢
