### ISSUE TITLE
消费者的消费问题

### ISSUE THREAD

**Issue by yangbocheng** [NewLifeX/NewLife.RocketMQ#49]
我在使用的时候发现了2个问题，能否指教
1.经过测试，消费端消费的能力似乎等同于java版的有序消费模式(MessageListenerOrderly), 见
https://www.jb51.net/article/215566.htm
我的环境是1个topic  2个队列，共1000条消息。  1个消费者，BatchSize默认32，使用Thread.Sleep(100) 模拟耗时，最后全部消费完，耗时53s，平均每个包耗时53ms, 与上面网址java版的MessageListenerOrderly速度相当。 而非java默认情况下的并发消费模式MessageListenerConcurrently

2.消费完了，返回的也是true。但是为什么从web-console上看到的 [主题]-nx_test-状态 的2个队列的最小位点始终为0。 [主题]-nx_test-状态-consumer管理里面的代理者位点和消费者位点是相同的，差值为0； 而消息的traceType全部是PULL,

下面分别是代码，和图：图中已经生产了3000条组左右的消息
```csharp
var mq111 = new Producer()
{
    NameServerAddress = "127.0.0.1:9876",
    Log = XTrace.Log,
};
//链接默认的topic
mq111.Start();
mq111.CreateTopic("nx_test", 2);
mq111.Stop();
mq111.Dispose();
var mq = new Producer
{
    Topic = "nx_test",
    NameServerAddress = "127.0.0.1:9876",
    Log = XTrace.Log,
};
mq.Start();
for (var i = 0; i < 1001; i++)
{
    var str = "学新" + i +$" publishtime = {DateTime.Now:HHmmss.fff}";
    var sr = mq.Publish(str, "TagA");
}
Console.WriteLine("正在处理.....");
Console.ReadLine();
```
```csharp
var consumer = new Consumer
{
    Topic = "nx_test",
    Group = "nx_g1",
    NameServerAddress = "127.0.0.1:9876",
    //FromLastOffset = false,
    //BatchSize = 3,
    Log = XTrace.Log,
};

consumer.OnConsume = (q, ms) =>
{
    XTrace.WriteLine("[{0}@{1}]收到消息[{2}] threadId={3} ms.Length={4}", q.BrokerName, q.QueueId, ms.Length, Thread.CurrentThread.ManagedThreadId,ms.Length);
    Console.WriteLine(
        $"[{q.BrokerName}@{q.QueueId}]收到消息[{ms.Length}] threadId={Thread.CurrentThread.ManagedThreadId} ms.Length={ms.Length}");
    foreach (var item in ms.ToList())
    {
        XTrace.WriteLine($"消息：主键【{item.Keys}】，产生时间【{item.BornTimestamp.ToDateTime()}】，内容【{item.Body.ToStr()}】queueid={q.QueueId} threadid={Thread.CurrentThread.ManagedThreadId}");
        Console.WriteLine(
            $"消息：主键【{ item.Keys}】，产生时间【{ item.BornTimestamp.ToDateTime()}】，内容【{ item.Body.ToStr()}】");
        Thread.Sleep(100);
    }
    return true;
};
consumer.Start();
Console.WriteLine("正在处理.....按任意键停止消费");
Console.ReadLine();
consumer.Stop();
consumer.Dispose();
Console.WriteLine("consumer");
```

![image](https://user-images.githubusercontent.com/32633109/210489344-d4950bd9-34a5-4f0c-81f4-49adba536113.png)
![image](https://user-images.githubusercontent.com/32633109/210489377-0c120c6f-7aeb-4912-a638-b88d9186f177.png)
![image](https://user-images.githubusercontent.com/32633109/210489621-aee5653b-ead4-4f34-8c77-70db338eaeb3.png)

**Comment by yangbocheng** [comment]
谢谢作者回复，但是我想问的更深一点。因为是一些个人的理解和猜测，如有错误，请不吝指出
对于第一个问题：我通过实验发现newlife的consumer默认实现，是先获取需要处理多少个queue, 然后建立同等数量的线程，1对1去处理。 因此每个队列的处理顺序是一定顺序的，因此1000个100ms的任务，分为2个队列，consumer处理时用了2个线程工作(实际上用到了线程池，但是等同于2个线程工作)。因此理论上consumer每100ms能处理2个任务，按统计学那么1个任务平均50ms，这与实际结果53ms是差多不的。  这与java的MessageListenerOrderly的结果似乎相同，因此我猜测newlife的默认实现等同于MessageListenerOrderly

但是java版默认使用的是MessageListenerConcurrently，按照我的理解。同样上面的环境下，consumer被分配处理2个队列，但是consumer可能会用线程池生成10个线程去并行处理这2个队列，java的 这种情况下，当然每个队列的各个任务不保证先后完成顺序，因此各个队列的消费情况是乱序的。
引用  https://copyfuture.com/blogs-details/202212292041048957

因此猜想java的默认实现使得在不关注顺序处理的情况下，消费能力可能是显著高于本包的默认实现的顺序消费的。感觉这有可能会成为一个痛点。

对于第2个问题，我似乎看到过资料minoffset会影响到rocketmq对已消费资源的空间回收。这个值一直为0，可能有什么原因吗。 因为这个现象，担心rocketmq会出现未知的错误

**Comment by nnhy** [comment]
你的理解非常正确！
正式为了稳定有序消费，所以每个queue开了一个线程，顺序处理消息。
该线程每成功处理一批消息（return true），调度器就会把这批消息的最大偏移量设置回去rocketmq服务器，告诉服务器，这个消费者在这个queue的最后消费offset是哪里，然后客户端按照这个offset开始下一轮PULL拉取消息。
加入每个queue对应多个线程，拉取消费没有问题，但是设置offset的时候怎么办呢？rocketmq服务器只会有一个地方记录这个消费者在这个queue上的offset，多个线程同时设置，就可能混乱，导致消息被重复消费。

在每queue单线程的模式下，提升吞吐的办法是，加大批大小，然后批量处理这次拉取回来的消息，当所有消息都处理完成以后，再去设置offset，从而避免混乱问题。

最后，这个组件设计于2018年初，为了解决官方rocketmq的.net客户端不稳定问题（内部调用C++）。在中通，每天消费100亿消息，queue分了256，消费用了4~8台服务器。

**Comment by yangbocheng** [comment]
谢谢，经过博主的提示。我有个新的思路，不知道对不对。
如果要实现MessageListenerConcurrently，最简单的方法就是 在OnConsumeAsync ，处理全部任务时，使用task, 及task.WhenAll 这样 消息的消费过程就全部是乱序，并且使用到线程池。  
这种情况下，原先的设计就等同于使用queue.count的线程去批量拉取rocketmq消息。 然后线程池共同消费全部的消息。 最后的效果就是拉取和消费都是使用线程池，我猜测这种情况下等同于java的MessageListenerConcurrently效果。
进一步的话，可以继承Consumer重写消费过程，以实现可自定义的顺序或者共同消费

还有一个问题我想请教下， 请问如果在OnConsume里爆出异常，和主动返回false2种情况下，后续这批消息会怎么样呢，能否简单介绍。

衷心希望组件越来越好，感谢！

**Comment by nnhy** [comment]
核心就是在异步的OnConsumeAsync事件里面 await Task.WhenAll。

重载 OnConsume 和写事件效果是一样的，因为默认的OnConsume实现就是触发事件。

返回false跟抛出异常，结果是一样的，都是跳过了UpdateOffset，然后下一次轮询再次拉取同样的消息。

在消费失败这个事情上，RocketMQ的标准方案是把消息放入另一个队列，静默一定时间后再次消费。
我们NewLife.RocketMQ没有实现这么复杂的机制，可以留给用户自己搞。
从架构设计上来讲，但凡能够控制返回false的时候，就不要轻易抛出异常。

**Comment by yangbocheng** [comment]
理解了，谢谢！
