### ISSUE TITLE
请问消费者支持push模式吗

### ISSUE THREAD

**Issue by anzhonghui** [NewLifeX/NewLife.RocketMQ#50]

**Comment by nnhy** [comment]
现在的轮询异步阻塞PULL，等同于PUSH，只要有发布消息，消费者马上能够拿到，几乎没有延迟

**Comment by anzhonghui** [comment]
好嘞，非常感谢，请问咱的客户端最新兼容的rocketmq的服务端的版本号是多少呀

**Comment by nnhy** [comment]
没有关注过rocketmq的版本，如果有兼容问题，可以提供一个测试环境，我们一起解决
