### ISSUE TITLE
有辦法支援 Broadcast 嗎

### ISSUE THREAD

**Issue by daship118** [NewLifeX/NewLife.RocketMQ#56]
目前只支援 Clustering，請問未來有開放 Broadcast 的方法嗎

**Comment by nnhy** [comment]
每个应用，使用不同的消费组（Group），也就是广播模式了。

**Comment by daship118** [comment]
> 每个应用，使用不同的消费组（Group），也就是广播模式了。

由於應用程式可以 scale out，group 就會是同樣的，也就是只有某幾台才會收到，在實際應用上，有些場景是需要每一台都收到的

**Comment by nnhy** [comment]
如果想在 scale out 的情况下，仍然保证每台都能收到全部消息，可以考虑使用动态group，确保每个实例都不一样。

另外，可以帮忙找一找RocketMQ关于广播模式的资料，如果资料明确，我们直接支持。
