### ISSUE TITLE
支持 RocketMQ 5.0 POP 消费模式

### ISSUE THREAD

**Issue by lindexi** [NewLifeX/NewLife.RocketMQ#58]
RocketMQ 5.0 中引入了一种新的消费模式：Pop 消费模式。

我们知道 RocketMQ 原来有两种消费模式：Pull 模式消费和 Push 模式消费，其中 Push 模式指的是 Broker 将消息主动“推送”给消费者，它的背后其实是消费者在不断地 Pull 消息来实现类似于 Broker “推”消息给消费者的效果。

新引入的 Pop 消费模式主要是用于 Push 消费时将拉消息的动作替换成 Pop 。Pop 消费的行为和 Pull 消费很像，区别在于 Pop 消费的重平衡是在 Broker 端做的，而之前的 Pull 和 Push 消费都是由客户端完成重平衡。

优点：

- 负载均衡放在服务端完成，可支持超过 Queue 数量的消费者
- 解决某个消费者 hang （挂机、僵尸）导致对应的 Queue 队列任务堆积没有被消费

参考：

- [RocketMQ 5.0 POP 消费模式探秘-阿里云开发者社区](https://developer.aliyun.com/article/801815 )
- [RocketMQ 5.0: POP 消费模式 原理详解 & 源码解析 - 知乎](https://zhuanlan.zhihu.com/p/592172135 )

**Comment by nnhy** [comment]
经测试支持 Apache RocketMQ v5.3 ！

v2.6.2024.1004 支持RocketMQ v5.3，在公网测试通过。默认内网broker地址替换为公网地址。https://github.com/NewLifeX/NewLife.RocketMQ/commit/006817ea918d48c83b2fb0f1318a8a3b339f9528
