### ISSUE TITLE
是否支持集群消费

### ISSUE THREAD

**Issue by anzhonghui** [NewLifeX/NewLife.RocketMQ#59]
请问是否支持多节点消费，我们测试的时候发现在3个服务器上消费同一个topic数据，也是同一个消费组，发现三个节点都会消费同一条数据

**Comment by nnhy** [comment]
默认集群消费，同一个消费组的多个实例，分享数据。
从日志可以看到，各个实例分到的queue不同。

**Comment by anzhonghui** [comment]
您好，但是我们用三台机器测试，发现都会消费同一个queue的消息，他们的消费组都是相同的，并且在三台实例上，请问是我们的配置有问题吗？
![企业微信截图_33ee9947-30ee-4321-bafb-6c7e763bbc81](https://github.com/NewLifeX/NewLife.RocketMQ/assets/104904136/110afaba-7f7b-4663-ba83-ad3cffb3e2c9)
![企业微信截图_1c1ea23e-ae29-4ee4-a714-0f84644c8e2e](https://github.com/NewLifeX/NewLife.RocketMQ/assets/104904136/052bf76f-1ef2-4d06-bba4-75f32456bfd2)
![企业微信截图_a0754985-9411-48ab-8a89-f03cdb87d798](https://github.com/NewLifeX/NewLife.RocketMQ/assets/104904136/d53e57b4-56b8-40d4-a669-620bab012441)

**Comment by anzhonghui** [comment]
消费者的代码也是我们参考官网的
![image](https://github.com/NewLifeX/NewLife.RocketMQ/assets/104904136/6d346935-789f-429a-ac6c-a2fb49e78246)

**Comment by nnhy** [comment]
1，确保Consumer.MessageModel设置为集群而不是广播
2，Consumer.Log=XTrace.Log，看Log目录下的日志

从日志，就可以知道一切问题

**Comment by anzhonghui** [comment]
您好，我没有Consumer.MessageModel在代码里如何配置，我尝试在两台机器上开启了XTrace.Log，通过日志看他们确实都在处理相同的queue
![image](https://github.com/NewLifeX/NewLife.RocketMQ/assets/104904136/30f0296a-5988-4085-99f1-2d65f7f47006)
![image](https://github.com/NewLifeX/NewLife.RocketMQ/assets/104904136/40ee4a6b-d202-4a1a-9340-a7619237d33e)

**Comment by anzhonghui** [comment]
我们代码中没有做相关设置，我看您代码里默认是集群消费
![企业微信截图_f3621c3f-ca43-4973-b1b6-74968b694b49](https://github.com/NewLifeX/NewLife.RocketMQ/assets/104904136/1f306974-bc52-419f-8ddf-61a0e99e2ed3)

**Comment by nnhy** [comment]
从日志来看，两台应用相差5分钟，不确定是否双方没有感知到节点变更，不知道对方存住。
另外，你用的组件版本是2022年5月，最后这张截图是2023年5月的代码

**Comment by nnhy** [comment]
检查了平衡算法，应该是没有问题的。
每次拉取消费者列表，然后均分队列分片。

**Comment by anzhonghui** [comment]
好的，谢谢您，我再尝试一下
