### ISSUE TITLE
Tag 的支持

### ISSUE THREAD

**Issue by nodyang** [NewLifeX/NewLife.RocketMQ#6]
能否支持 opic、Tag

**Comment by xi3892** [comment]
暂时没有支持tag功能，后续会考虑增加该部分的功能，目前使用场景是直接在业务代码中进行过滤

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/70426614-4c013280-1aae-11ea-905a-f1d06470db71.png)
我看zhushi注释了。我放开 是不是可以支持简单的

**Comment by nnhy** [comment]
即使放开，也需要相应代码支持
