### ISSUE TITLE
rocketmq origin msgid  is diffent with sdk parse

### ISSUE THREAD

**Issue by lsw2012abc** [NewLifeX/NewLife.RocketMQ#60]
原始消息属性，其中UNIQ_KEY为：`AC17043B001E1E9804B955C1DE160B6C`
`<html>
<body>

{"REAL_TOPIC":"zyq_mq_contract_tby_topic","sw8-x":"0-1684309168662","sw8":"1-NzgwOWIwNmE1ZDBmNDQ3ZTlhZDFmNGFmNTA5YWIzYWEuNDAwLjE2ODQzMDkxNjg2NjIwMjU1-NzgwOWIwNmE1ZDBmNDQ3ZTlhZDFmNGFmNTA5YWIzYWEuNDAwLjE2ODQzMDkxNjg2NjIwMjU0-0-cWEtZS1zaWduYXR1cmUtc2VydmVy-MTcyLjIzLjQuNTlAOTE5NTQ1NGQwNjFiNGE3Zjk2NDRjMGMxZDc3ZTVlZDg=-Um9ja2V0TVEvenlxX21xX2NvbnRyYWN0X3RieV90b3BpYy9Qcm9kdWNlcg==-cm9ja2V0bXExLXFhLnl6dy5jbjo5ODc2O3JvY2tldG1xMi1xYS55encuY246OTg3Njtyb2NrZXRtcTMtcWEueXp3LmNuOjk4NzY=","id":"5cdfe77e-e743-3156-ded2-010abbb7a31e","UNIQ_KEY":"AC17043B001E1E9804B955C1DE160B6C","WAIT":"false","contentType":"application/json","DELAY":"1","TAGS":"contract_info_tag","timestamp":"1684309168662","REAL_QID":"1"}
--

</body>
</html>`

版本为【2.2.2023.401】的SDK解析解析出来之后，msgid：`AC1001740000BCFD000000573DA3275F` 。
能找时间看看是因为协议问题导致解析逻辑变了吗

**Comment by nnhy** [comment]
sdk客户端的msgid也是来自服务端接口返回

**Comment by nnhy** [comment]
服务器版本 4.x，发布后得到的msgid去控制台查，能够查到消息本身
