### ISSUE TITLE
用线程创建了3个customer,程序开启一段时间后，就不消费了

### ISSUE THREAD

**Issue by zt72065036** [NewLifeX/NewLife.RocketMQ#61]
for (int i = 0; i < 3; i++)
                {
                    var j = i;
                    Task.Factory.StartNew(() =>
                          {
                              //测试消费消息
                              var consumer = new NewLife.RocketMQ.Consumer
                              {
                                  Topic = "bb",
                                  NameServerAddress = "xx",
                                  BatchSize = 3,
                                  Group = "bbgroup"
                              };
                              consumer.Start();
                              consumer.OnConsume = (q, ms) =>
                              {
                                  string mInfo = $"datetime={DateTime.Now},BrokerName={q.BrokerName},QueueId={q.QueueId},Length={ms.Length}";
                                  Console.WriteLine(mInfo);
                                  if (q.QueueId % 3 == j)
                                  {
                                      //string mInfo = $"BrokerName={q.BrokerName},QueueId={q.QueueId},Length={ms.Length}";
                                      //Console.WriteLine(mInfo);
                                      LogHelper.Information("RocketMQConsumer" + j, mInfo);
                                      foreach (var item in ms.ToList())
                                      {
                                          string msg = $"消息：msgId={item.MsgId},key={item.Keys}，产生时间【{item.BornTimestamp.ToDateTime()}】，内容>{item.BodyString}";
                                          //Console.WriteLine(msg);
                                          LogHelper.Information("RocketMQConsumer" + j, msg);
                                          //chat.SendMessageMQ(rtMQHelper.getSingnalModel(item.Body.ToString()));
                                      }
                                      //   return false;//通知消息队：不消费消息
                                      return true;        //通知消息队：消费了消息
                                  }
                                  else
                                  {
                                      return true;
                                  }
                              };
                          });
                }
请问是不是这种写法有问题？

**Comment by nnhy** [comment]
consumer孤零零的，过一会gc就该来收割它啦。
可以搞一个数组，把这些消费者对象管理起来

**Comment by nnhy** [comment]
创建消费者的时候，没有必要异步，直接for循环好了，因为Start只是启动内部线程，并不阻塞

**Comment by zt72065036** [comment]
> consumer孤零零的，过一会gc就该来收割它啦。 可以搞一个数组，把这些消费者对象管理起来

怎么管理呢？定时判断消费者是否存在吗？不存在了就重新创建一个新的？

**Comment by nnhy** [comment]
弄一个全局变量，或者静态变量都行，只要有引用，GC就不会销毁它

**Comment by zt72065036** [comment]
> 弄一个全局变量，或者静态变量都行，只要有引用，GC就不会销毁它

好的，谢谢，另外一个问题，请有可以获取topic下queueid的方法吗？尝试用Queues，好像不行

**Comment by zt72065036** [comment]
> 弄一个全局变量，或者静态变量都行，只要有引用，GC就不会销毁它

 public static List<Consumer> listConsumer = new List<Consumer>();
        public IConfiguration _configuration { get; }
        public RocketMQConsumer(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public void Start()
        {
            //Task.Factory.StartNew(() =>
            //{
            //RocketMQHelper rtMQHelper = new RocketMQHelper();
            //ChatManager chat = new ChatManager(_configuration);
            for (int i = 0; i < 3; i++)
            {
                //    var j = i;
                //测试消费消息
                var consumer = new Consumer
                    {
                        Topic = "vomcccntest",
                        NameServerAddress = "it-rocketmq-test-1.vivo.xyz:9876;it-rocketmq-test-2.vivo.xyz:9876;",
                        BatchSize = 3,
                        Group = "vomcccntest"
                    };
                    consumer.OnConsume = (q, ms) =>
                    {
                        string mInfo = $"datetime={DateTime.Now},BrokerName={q.BrokerName},QueueId={q.QueueId},Length={ms.Length}";
                        Console.WriteLine(mInfo);
                        //if (q.QueueId % 3 == j)
                        //{
                            foreach (var item in ms.ToList())
                            {
                                string msg = $"消息：msgId={item.MsgId},key={item.Keys}，产生时间【{item.BornTimestamp.ToDateTime()}】，内容>{item.BodyString}";
                                    //Console.WriteLine(msg);
                                    LogHelper.Information("RocketMQConsumer", msg);
                                    //chat.SendMessageMQ(rtMQHelper.getSingnalModel(item.Body.ToString()));
                                }
                                //   return false;//通知消息队：不消费消息
                                return true;        //通知消息队：消费了消息
                        //}
                        //else
                        //{
                        //    return true;
                        //}
                    };
                    consumer.Start();
                    listConsumer.Add(consumer);
               }
}
这样用listConsumer来管理，还是只会执行一次，麻烦帮看下，谢谢

**Comment by nnhy** [comment]
嗯，是这样，代码没有错。
可以看看日志。

**Comment by zt72065036** [comment]
感谢团队大佬贡献

**Comment by nnhy** [comment]
问题解决了吗？
