### ISSUE TITLE
消费者会时不时的位移消费位置

### ISSUE THREAD

**Issue by zt72065036** [NewLifeX/NewLife.RocketMQ#64]
for (int i = 0; i < item.new_queuenum; i++)
                        {
                            var j = i;
                            var consumer = new Consumer
                            {
                                Topic = item.new_topic,
                                NameServerAddress = nameServerAddress,
                                BatchSize = item.new_pullqty,
                                Group = item.new_topic,
                                
                            };
                            consumer.OnConsume = (q, ms) =>
                            {
                                if (q.QueueId % item.new_queuenum == j)
                                {
                                    string mInfo = $"BrokerName={q.BrokerName},QueueId={q.QueueId},Length={ms.Length}";
                                    LogHelper.Information(q.BrokerName + "RocketMQConsumer" + j, mInfo);
                                    foreach (var item in ms.ToList())
                                    {
                                        try
                                        {
                                            string msg = $"消息：msgId={item.MsgId},key={item.Keys}，产生时间【{item.BornTimestamp.ToDateTime()}】，内容>{item.BodyString}";
                                            LogHelper.Information(q.BrokerName + "RocketMQConsumer" + j, msg);
                                            
                                        }
                                        catch (Exception ex)
                                        {
                                            LogHelper.Information("Error", ex.Message);
                                        }
                                    }
                                }
                                return true;        //通知消息队：消费了消息
                            };
                            consumer.Start();
                            listConsumer.Add(consumer);
                        }
代码如上，消费者重启时，有时候会把消费位置给变更；比如原来消费到100位置了，重启后又到0重新开始的情况，会是什么？

**Comment by nnhy** [comment]
消费时，如果没有抛出异常，它本身就会自动确认消息，从而让偏移位置前移

**Comment by zt72065036** [comment]
> 消费时，如果没有抛出异常，它本身就会自动确认消息，从而让偏移位置前移

我的消费者是没有异常，重新启动就位置异常了，不知道是不是我多端消费的原因。
另外我上面的写法，很吃内存和CPU会是什么问题？

**Comment by nnhy** [comment]
内存暴涨的问题已经找到。

Register返回值需要Dispose，否则会导致内存泄漏 · NewLifeX/X@11fa910
https://github.com/NewLifeX/X/commit/11fa9105f196f4d64a5c08d39ebbe51b1ea6b1ea

**Comment by nnhy** [comment]
该问题源自于今年5月16日，核心网络库消息发送层增加了异步通知，持续挂载委托事件造成了内存泄漏。

修正方案有二：
1，回滚到NewLife.RocketMQ的上一个正式版，即0401
2，使用最新代码编译新版本

现在nuget上0601包已禁用。
