### ISSUE TITLE
用了最新版的NewLife.Core.dll还是内存泄露

### ISSUE THREAD

**Issue by zt72065036** [NewLifeX/NewLife.RocketMQ#65]
我用的版本是10.3.2023.608，放到服务器上跑着跑着，内存又占2G多了，会是什么问题？谢谢解答

**Comment by nnhy** [comment]
从Nugget引用最新beta版的 newlife.core 和 newlife.rocketmq 即可

**Comment by zt72065036** [comment]
> 从Nugget引用最新beta版的 newlife.core 和 newlife.rocketmq 即可

用beta版本，也会占用内容到2G的情况

**Comment by nnhy** [comment]
使用nuget的最新版本 应该是没有问题的，看一下日志输出的版本号，是不是没有更新成功

**Comment by zt72065036** [comment]
> 使用nuget的最新版本 应该是没有问题的，看一下日志输出的版本号，是不是没有更新成功

用的10.4.2023.707版本的Newlife.Core,放服务器上2、3天后，内存点到10多G了
15:23:00.304 34 Y 1 NewLife.Core v10.4.2023.0707 Build 2023-07-07 .NET Core 3.1

**Comment by nnhy** [comment]
用 dotMemory 抓个dump分析一下，看是哪个地方占用过大的内存

**Comment by nnhy** [comment]
该问题已解决并验证通过！
有问题的版本已从nuget撤下
