### ISSUE TITLE
有没有顺序消息推送的例子？

### ISSUE THREAD

**Issue by anchurcn** [NewLifeX/NewLife.RocketMQ#70]
你好，请问有没有顺序消息推送的例子？我根据[该commit](https://github.com/NewLifeX/NewLife.RocketMQ/commit/e3ae9dd73884e593f66499f93d0973701f599e0c)得知顺序消息需要在发送消息前 select 获取一个 queue，之后发布消息都指定该 queue 应该就能发送顺序消息了。不知道还有没有其他需要注意的点，比如 UnitMode 需要设置成什么，或者其他的配置才能保证消息的顺序发布。我能保证发布是单线程的。

**Comment by nnhy** [comment]
只需要自己Select得到特定queue，向里面发布消息即可。推送到这个queue的消息都是有序的，消费顺序也能确定。

**Comment by anchurcn** [comment]
@nnhy 好的，感谢您抽出宝贵的时间解答。
