### ISSUE TITLE
连接rocketmq dledger集群，集群重新选主后，rocketmq连接不上

### ISSUE THREAD

**Issue by leili-ncut** [NewLifeX/NewLife.RocketMQ#71]
使用的版本：2.4.2023.803
rocketmq集群重新选主后，必须重启服务，rocketmq才能正常连接，不能自动重连。

**Comment by nnhy** [comment]
我也遇到了这个问题，最近比较忙，还没有时间处理。

修改思路就是，检测到topic的broker列表有变化以后，重新初始化所有 BrokerClient

**Comment by nnhy** [comment]
早两天某个Topic下的Broker进行扩容，Broker信息有改变，应用这边能够自动感知到，无需重启。
使用的是nuget上最新版本。

你说的broker重新选主以后，如果broker集群信息能够更新到NameServer，rocketmq客户端组件理论上是能够自动更新的。
