### ISSUE TITLE
请教一下，如何在出现异常时手动关闭程序，而不是自动重试

### ISSUE THREAD

**Issue by zbsBrave** [NewLifeX/NewLife.RocketMQ#72]
项目中很多这种异常 ，而且后续也无法正常连接上mq，即使mq的ip地址能ping通。
所以我想在出现异常时手动停止，请问我该如何做

09:58:57.651 96 Y T System.AggregateException: 发生一个或多个错误。 ---> System.Threading.Tasks.TaskCanceledException: 已取消一个任务。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   在 NewLife.RocketMQ.ClusterClient.Invoke(RequestCode request, Object body, Object extFields, Boolean ignoreError)
   在 NewLife.RocketMQ.NameClient.GetRouteInfo(String topic)
   在 NewLife.RocketMQ.NameClient.DoWork(Object state)
   在 NewLife.Threading.TimerScheduler.Execute(Obje
09:59:05.399  3 N T 任务 [4]TimerX.CopyNow (500ms) 耗时过长 2,806ms，建议使用异步任务Async=true

**Comment by nnhy** [comment]
这是NameClient定时刷新Topic所在Broker信息，即使请求失败，也不影响已有Broker的正常使用。
除非Broker地址信息变更，同时NameClient又无法获取新的Broker信息。

从最后一行日志来看，CopyNow出现超时，往往因为这个程序非常繁忙。
可以朝这个方向去检查分析问题。

**Comment by zbsBrave** [comment]
非常感谢。
我的程序是一个window console，功能只是监听消息队列并处理。
当出现这个异常时，整个日志中都是打印的都是这种内容，偶尔夹杂着连接超时的提示，这时已经接受不到消息并处理了，所以它在出现这种情况时其实并不繁忙。
然后这个程序是部署在一台虚拟的window server上，出现这个情况后，window server就陷入假死的状态，根本无法连接上。我无法判断是不是因为这个引起的，所以想在它出现这种异常时，直接把程序关掉。

**Comment by nnhy** [comment]
如果是虚拟机遇到这种情况，根据你的描述，大概率就是这台虚拟机资源不足（宿主机没有资源供其调度）。
这个时候，虚拟机上的任何程序都将无法执行，包括你的应用和操作系统应用在内，所以恐怕你很难实现连不上的时候自动关闭。

**Comment by nnhy** [comment]
你可以考虑在虚拟机上安装StarAgent，接入自己的星尘服务端。
在虚拟机性能不足的时候，StarAgent将会监控到，在调度资源恢复的时候，上报给服务端，起码我们有了一个抓手，能够得知系统资源的确紧张。

**Comment by zbsBrave** [comment]
后续没出现这个问题了
