### ISSUE TITLE
能不能设置任务超时时间

### ISSUE THREAD

**Issue by zbsBrave** [NewLifeX/NewLife.RocketMQ#75]
问题：消费者执行任务时卡住了，导致整个服务无法继续接受消息。
请问能不能设置任务的超时时间，超时后主动关闭这个任务，继续接受新任务。

**Comment by nnhy** [comment]
在消费到消息时，可以用task执行处理任务，并wait一段时间等待返回。
如果处理超时没有返回，则取消task，并且确认消息。

**Comment by nnhy** [comment]
经测试支持 Apache RocketMQ v5.3 ！

v2.6.2024.1004 支持RocketMQ v5.3，在公网测试通过。默认内网broker地址替换为公网地址。https://github.com/NewLifeX/NewLife.RocketMQ/commit/006817ea918d48c83b2fb0f1318a8a3b339f9528
