### ISSUE TITLE
连接5.2.0版本的集群后，返回system_error错误

### ISSUE THREAD

**Issue by AlexTian2012** [NewLifeX/NewLife.RocketMQ#78]
之前链接4.9版本RockentMQ正常，RocketMQ升级5.2.0后，可以正常消费消息，但是发布消息报服务器错误，system_error,详细错误消息如下，烦请解答，谢谢
====================================================================
====================================================================
NewLife.RocketMQ.Protocol.ResponseException
  HResult=0x80131500
  Message=SYSTEM_ERROR: java.lang.NullPointerException
  Source=NewLife.RocketMQ
  StackTrace:
   在 NewLife.RocketMQ.Producer.Publish(Message message, MessageQueue queue, Int32 timeout)
   在 NewLife.RocketMQ.Producer.Publish(Object body, Int32 timeout)
   在 ConsoleApp1.NewLifeMQ.test() 在 C:\Users\Alex.Tien\source\repos\ConsoleApp1\ConsoleApp1\NewLifeMQ.cs 中: 第 30 行
   在 Program.<Main>$(String[] args) 在 C:\Users\Alex.Tien\source\repos\ConsoleApp1\ConsoleApp1\Program.cs 中: 第 5 行

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    ConsoleApp1.NewLifeMQ.test() (位于 NewLifeMQ.cs 中)
    Program.<Main>$(string[]) (位于 Program.cs 中)

**Comment by nnhy** [comment]
目前尚未支持rocketmq5.x。
你是第一个说明支持rocketmq5.x消费的用户。

**Comment by 3d-fey** [comment]
> 目前尚未支持rocketmq5.x。 你是第一个说明支持rocketmq5.x消费的用户。

我看可以发消息，但是消费消息会有以下错误

15:17:22.853  9 Y TP System.NullReferenceException: Object reference not set to an instance of an object.
   at NewLife.RocketMQ.Consumer.ConsumerStatesSpecialJsonHandler(Packet payload)
   at NewLife.RocketMQ.Consumer.InitOffsetAsync(CancellationToken cancellationToken)
   at NewLife.RocketMQ.Consumer.Rebalance()
   at NewLife.RocketMQ.Consumer.CheckGroup(Object state)

**Comment by nnhy** [comment]
> > 目前尚未支持rocketmq5.x。 你是第一个说明支持rocketmq5.x消费的用户。
> 
> 我看可以发消息，但是消费消息会有以下错误
> 
> 15:17:22.853 9 Y TP System.NullReferenceException: Object reference not set to an instance of an object. at NewLife.RocketMQ.Consumer.ConsumerStatesSpecialJsonHandler(Packet payload) at NewLife.RocketMQ.Consumer.InitOffsetAsync(CancellationToken cancellationToken) at NewLife.RocketMQ.Consumer.Rebalance() at NewLife.RocketMQ.Consumer.CheckGroup(Object state)

这里应该是解析响应json出错了

**Comment by nnhy** [comment]
经测试支持 Apache RocketMQ v5.3 ！

v2.6.2024.1004 支持RocketMQ v5.3，在公网测试通过。默认内网broker地址替换为公网地址。https://github.com/NewLifeX/NewLife.RocketMQ/commit/006817ea918d48c83b2fb0f1318a8a3b339f9528
