### ISSUE TITLE
可以提供Pull Message 的例子嗎？

### ISSUE THREAD

**Issue by lingkingtong** [NewLifeX/NewLife.RocketMQ#8]
目前在Test Project 裏面只有Push 的方面，並沒有Pull 的方法，如果能提供真的是感激不盡。

**Comment by nnhy** [comment]
private static Consumer _consumer;
static void Test2()
{
    var consumer = new Consumer
    {
        Topic = "nx_test",
        Group = "test",
        NameServerAddress = "127.0.0.1:9876",

        FromLastOffset = false,
        //SkipOverStoredMsgCount = 0,
        //BatchSize = 20,

        Log = XTrace.Log,
        ClientLog = XTrace.Log,
    };

    consumer.OnConsume = OnConsume;

    consumer.Configure(MqSetting.Current);
    consumer.Start();

    _consumer = consumer;
}

消费端就是你说的Pull，内部有线程池调度，然后触发事件
