### ISSUE TITLE
对于c#的sdk 为何会针对Message类的BodyString删除set接口？

### ISSUE THREAD

**Issue by Farggle** [NewLifeX/NewLife.RocketMQ#80]
`
namespace NewLife.RocketMQ.Protocol
{
    // 摘要: 
    //     消息
    public class Message
    {
        public Message();

        // 摘要: 
        //     消息体
        [XmlIgnore]
        public byte[] Body { get; set; }
        //
        // 摘要: 
        //     消息体。字符串格式
        public string BodyString { get; }
        //
        // 摘要: 
        //     延迟时间等级
        public int DelayTimeLevel { get; set; }
        //
        // 摘要: 
        //     标记
        public int Flag { get; set; }
        //
        // 摘要: 
        //     键
        public string Keys { get; set; }
        //
        // 摘要: 
        //     标签
        public string Tags { get; set; }
        //
        // 摘要: 
        //     主题
        public string Topic { get; set; }
        //
        // 摘要: 
        //     等待存储消息
        public bool WaitStoreMsgOK { get; set; }

        // 摘要: 
        //     获取属性
        public string GetProperties();
        //
        // 摘要: 
        //     分析字典属性
        //
        // 参数: 
        //   properties:
        public IDictionary<string, string> ParseProperties(string properties);
        //
        // 摘要: 
        //     设置消息体
        //
        // 参数: 
        //   body:
        public void SetBody(object body);
        //
        // 摘要: 
        //     友好字符串
        public override string ToString();
    }
}
`

**Comment by nnhy** [comment]
因为它是在使用时用Body转换得来。
其实BodyString也可以带set，直接赋值给Body即可，你可以提交PR

**Comment by Farggle** [comment]
> 因为它是在使用时用Body转换得来。 其实BodyString也可以带set，直接赋值给Body即可，你可以提交PR

是的，我就是觉得可以带set，就是不知道为啥要特意把set删掉，想知道删除的原因。因为有些时候直接设置bodyString是更方便的。
