### ISSUE TITLE
是否支持自动创建topic

### ISSUE THREAD

**Issue by yimiaoxiehou** [NewLifeX/NewLife.RocketMQ#86]
在4.7.1的双broker集群下，使用 productTest 的 unit test， 发现可以创建主题，但不可以在不插件 topic 的情况下，发送消息，会报 TOPIC_NOT_EXIST， No topic route info in name server for the topic， 但是 autoCreateTopicEnable 已打开，且 java 端可以通过该场景

**Comment by nnhy** [comment]
可以抓包看看java发布消息给新topic时，都传递了哪些字段，把json发出来。
我们发布消息到新topic的时候，也可以带上相同参数。

**Comment by yimiaoxiehou** [comment]
@nnhy 第一次写 c# 代码，轻喷

**Comment by nnhy** [comment]
代码写得挺好的。可有测试通过？

**Comment by yimiaoxiehou** [comment]
> 代码写得挺好的。可有测试通过？
有点，修改了 productTest 测试过好几次， 
autocreatetopicenable=true 和 false 都测过了。结果和 java client一致
