### ISSUE TITLE
消费端无法拉取未被消费的信息

### ISSUE THREAD

**Issue by thxu** [NewLifeX/NewLife.RocketMQ#9]
`var consumer = new Consumer`
            `{`
                `//Server = "http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet",`
                `//AccessKey = "LTAINsp1qKfO61c5",`
                `//SecretKey = "BvX6DpQffUz8xKIQ0u13EMxBW6YJmp",`
                `Topic = "ntest",`
                `Group = "test",`
                `NameServerAddress = "127.0.0.1:9876",`
                `FromLastOffset = false,`
                `BatchSize = 20,`
                `Log = XTrace.Log,`
            `};`

在上面的示例代码中，

`FromLastOffset` 字段设置为true的情况下，消费端仅拉取程序启动后新投递到消息队列中的信息，

`FromLastOffset` 字段设置为false的情况下，消费端每次启动都将拉取消息队列中所有的信息，

可否新增一个配置项，让消费端启动时仅拉取消息队列中所有未被消费的消息。

**Comment by nnhy** [comment]
所有未消费，就是 FromLastOffset 了

**Comment by thxu** [comment]
我看了下NewLife.RocketMQ.Consumer类的源码

    // 查询偏移量，可能首次启动-1
    if (st.Offset < 0 && FromLastOffset)
    {
        var p = QueryOffset(mq);
        //if (p == -1) p = 0;
        //第一次消费新的队列，强制从消费最大偏移量的位置消费（避免由于第一次从最小偏移量消费而导致的数据大量积压问题）
        if (p <= 0) p = QueryMaxOffset(mq);
        st.Offset = st.CommitOffset = p;
        if (st.Offset >= 0) WriteLog("开始消费[{0}@{1}] Offset={2:n0}", mq.BrokerName, mq.QueueId, st.Offset);
    }
    // 拉取一批，阻塞等待
    var offset = st.Offset >= 0 ? st.Offset : 0;

在这份代码中，我发现消费者有一个逻辑是对于新的队列，程序会强制消费最大偏移量的位置，所以就出现了部分消息无法被消费的问题。

这样也导致了在部署程序时，必须严格按照先运行消费端，再运行生产端的流程部署，且在消息队列中如果有任何一个队列是空的队列的情况下，都不能重启消费端，否则都可能会出现重启后的消费端有部分消息无法消费的问题，这会增加我们部署的复杂程度。

可否新增一个配置项，允许用户自定义是否强制从最大偏移量处消费，或者允许客户自定义可跳过积压消息的数量呢。

**Comment by nnhy** [comment]
这个的确时一个问题，当初写的时候没想那么多就直接上了，你可以修改一下，提交个PR
